//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuddy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBuddy.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string AddFilesButton {
            get {
                return ResourceManager.GetString("AddFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddServiceButton {
            get {
                return ResourceManager.GetString("AddServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service.
        /// </summary>
        public static string AddServicePageTitle {
            get {
                return ResourceManager.GetString("AddServicePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vehicle.
        /// </summary>
        public static string AddVehicle {
            get {
                return ResourceManager.GetString("AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodywork, Interior &amp; Glass.
        /// </summary>
        public static string BodyInteriorAndGlass {
            get {
                return ResourceManager.GetString("BodyInteriorAndGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakes &amp; Suspension.
        /// </summary>
        public static string BrakesAndSuspension {
            get {
                return ResourceManager.GetString("BrakesAndSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete file.
        /// </summary>
        public static string DeleteFileText {
            get {
                return ResourceManager.GetString("DeleteFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Service.
        /// </summary>
        public static string DeleteServiceButton {
            get {
                return ResourceManager.GetString("DeleteServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vehicle.
        /// </summary>
        public static string DeleteVehicle {
            get {
                return ResourceManager.GetString("DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string EditServiceButton {
            get {
                return ResourceManager.GetString("EditServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string EditServicePageTitle {
            get {
                return ResourceManager.GetString("EditServicePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine &amp; Performance.
        /// </summary>
        public static string EngineAndPerformance {
            get {
                return ResourceManager.GetString("EngineAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid cost (numbers only).
        /// </summary>
        public static string EnterValidCost {
            get {
                return ResourceManager.GetString("EnterValidCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mileage (numbers only)..
        /// </summary>
        public static string EnterValidMileage {
            get {
                return ResourceManager.GetString("EnterValidMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter vehicle name:.
        /// </summary>
        public static string EnterVehicleName {
            get {
                return ResourceManager.GetString("EnterVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files attached to the service.
        /// </summary>
        public static string FilesAttachedLabel {
            get {
                return ResourceManager.GetString("FilesAttachedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Maintenance.
        /// </summary>
        public static string GeneralMaintenance {
            get {
                return ResourceManager.GetString("GeneralMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating, Cooling &amp; A/C.
        /// </summary>
        public static string HeatingAndCooling {
            get {
                return ResourceManager.GetString("HeatingAndCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Voltage Electronics.
        /// </summary>
        public static string HighVoltageElectronics {
            get {
                return ResourceManager.GetString("HighVoltageElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Voltage Electronics.
        /// </summary>
        public static string LowVoltageElectronics {
            get {
                return ResourceManager.GetString("LowVoltageElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vehicle.
        /// </summary>
        public static string NewVehicle {
            get {
                return ResourceManager.GetString("NewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Maintenance.
        /// </summary>
        public static string OtherMaintenance {
            get {
                return ResourceManager.GetString("OtherMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Service.
        /// </summary>
        public static string SaveServiceButton {
            get {
                return ResourceManager.GetString("SaveServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a service type.
        /// </summary>
        public static string SelectServiceType {
            get {
                return ResourceManager.GetString("SelectServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select service type.
        /// </summary>
        public static string SelectServiceTypeLabel {
            get {
                return ResourceManager.GetString("SelectServiceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Book.
        /// </summary>
        public static string ServiceBookTitle {
            get {
                return ResourceManager.GetString("ServiceBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;399&quot;.
        /// </summary>
        public static string ServiceCostEntryPlaceholder {
            get {
                return ResourceManager.GetString("ServiceCostEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service cost.
        /// </summary>
        public static string ServiceCostLabel {
            get {
                return ResourceManager.GetString("ServiceCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service date.
        /// </summary>
        public static string ServiceDateLabel {
            get {
                return ResourceManager.GetString("ServiceDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Car fixing company LLC&quot;.
        /// </summary>
        public static string ServicedByEntryPlaceholder {
            get {
                return ResourceManager.GetString("ServicedByEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviced by.
        /// </summary>
        public static string ServicedByLabel {
            get {
                return ResourceManager.GetString("ServicedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Changed the engine oil and filter...&quot;.
        /// </summary>
        public static string ServiceDescriptionEntryPlaceholder {
            get {
                return ResourceManager.GetString("ServiceDescriptionEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description.
        /// </summary>
        public static string ServiceDescriptionLabel {
            get {
                return ResourceManager.GetString("ServiceDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string ServiceDetailsPageTitle {
            get {
                return ResourceManager.GetString("ServiceDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;75000&quot;.
        /// </summary>
        public static string ServiceMileageEntryPlaceholder {
            get {
                return ResourceManager.GetString("ServiceMileageEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle mileage.
        /// </summary>
        public static string ServiceMileageLabel {
            get {
                return ResourceManager.GetString("ServiceMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesLabel {
            get {
                return ResourceManager.GetString("ServicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Routine maintenance&quot;.
        /// </summary>
        public static string ServiceTitleEntryPlaceholder {
            get {
                return ResourceManager.GetString("ServiceTitleEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service title.
        /// </summary>
        public static string ServiceTitleLabel {
            get {
                return ResourceManager.GetString("ServiceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type.
        /// </summary>
        public static string ServiceTypeLabel {
            get {
                return ResourceManager.GetString("ServiceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires &amp; Wheels.
        /// </summary>
        public static string TiresAndWheels {
            get {
                return ResourceManager.GetString("TiresAndWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission &amp; Drivetrain.
        /// </summary>
        public static string TransmissionAndDrivetrain {
            get {
                return ResourceManager.GetString("TransmissionAndDrivetrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Menu.
        /// </summary>
        public static string VehicleMenu {
            get {
                return ResourceManager.GetString("VehicleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
